=== elmarkrainz/accapto/Accapto_Generator/docs/accapto_model.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="org.accaptp" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="org.accaptp">

	<xs:element name="app" type="appType"/>

	<xs:complexType mixed="true" name="screenType">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element maxOccurs="unbounded" minOccurs="0" name="action" type="actionType"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="transition" type="transitionType"/>


			<xs:element maxOccurs="unbounded" minOccurs="0" name="input" type="inputType">
			</xs:element>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="output" type="outputType">
			</xs:element>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="subscreen" type="screenType"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
	</xs:complexType>




	<xs:complexType name="inputType">

		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>


	</xs:complexType>

	<xs:complexType name="outputType">
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>


	</xs:complexType>

	<xs:complexType name="actionType">

		<xs:attribute name="function" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>

	</xs:complexType>

	<xs:complexType name="appType">
		<xs:sequence minOccurs="1">
			<xs:element maxOccurs="5" minOccurs="1" name="profile" type="profileType"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="screen" type="screenType"/>

		</xs:sequence>

		<xs:attribute name="appname" type="xs:string"/>
		<xs:attribute name="package" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="transitionType">
		<xs:attribute name="target" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:simpleType name="profileType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="no restrictions"/>
			<xs:enumeration value="high contrast"/>
			<xs:enumeration value="blind"/>
			<xs:enumeration value="easy read"/>
			<xs:enumeration value="easy touch"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="baseTyp">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="description" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== elmarkrainz/accapto/Accapto_Generator/accapto_model_whereami.xml
<?xml version="1.0" encoding="UTF-8"?>

<p:app appname="Routing-App" package="org.accepto.app.routingapp"
	xmlns:p="org.accapto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="org.accaptp accapto_model.xsd ">
	<p:profile>no restrictions</p:profile>
		

	<p:screen name="RoutingStart">
			<p:action function="getLocation" name="Location bestimmen" description=""/>
			<p:output description="RoutingStart" name="RoutingStart" type="text" />
			<p:input name="Ziel" description="geben Sie das Ziel ein" />
			<p:transition description="open Routing" name="Routing OverView" target="RoutingOverView" />
			<p:transition description="open settings" name="Settings" target="Setting" />	
	</p:screen>
	
	<p:screen name="RoutingOverView">
			<p:output description="RoutingOverView" name="RoutingOverView" type="text" />
			<p:output description="RoutingOverView ..." name="gehen sie ..." type="text" />
			<p:transition description="open Routing" name="RoutingDetails" target="RoutingDetail" />
			<p:input description="RoutingOverView ..." name="gehen sie ..." type="text" />
	</p:screen>
	
	<p:screen name="RoutingDetail">
			<p:output description="Einstellungen" name="Einstellungen" type="text" />
	</p:screen>
	
	
	<p:screen name="Setting">
			<p:output description="Setting" name="Setting" type="text" />
			<p:transition description="open main" name="A11y Settings " target="A12ySettingsActivity" />
	</p:screen>
	
	
	<p:screen description="" name="Start">
		<p:output description="" name="Routing App" type="text" />
		<p:transition description="open Routing" name="Routing" target="RoutingStart" />
		<p:transition description="open settings" name="Settings" target="Setting" />	
	</p:screen>
	
	
</p:app>

=== elmarkrainz/accapto/Accapto_Generator/app_model.xml
<?xml version="1.0" encoding="UTF-8"?>

<p:app appname="DemoApp" package="org.accapto.demoapp"
xmlns:p="org.accapto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.accaptp accapto_model.xsd">
<p:profile>normal</p:profile>

<p:screen name="Start">
	
	<p:output name="APP DEMO" description="demo app" type="text" /> 
	<p:transition name="Start " description="start app" target="Main" /> 
	<p:transition name="Settings" description="modify app settings" target="Settings" /> 

</p:screen>

<p:screen name="Main">
	<p:output name="Demo App" description="som text for infos" type="text" /> 
	<p:input name="search something" description="enter a text" /> 
	<p:input name="the button" description="click the button" type="button"/> 
	<p:input name="Check it" description="check Stuff" type="checkbox" /> 
	<p:input name="Oe3" description="station oe3" type ="radio"/> 
	<p:input name="FM4" description="station fm4" type ="radio"/> 
	<p:action function="Peformask" name="Peform a Task" description="template for a function " /> 
</p:screen>



<p:screen name="Settings">
	<p:output name="Settings" description="app settings" type="text" /> 
</p:screen>



</p:app>

=== elmarkrainz/accapto/evaluation/app_model_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:app appname="DemoApp_2" package="org.accapto.demoapp"
	xmlns:p="org.accapto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="org.accaptp accapto_model.xsd">

	<p:profile>normal</p:profile>

	<p:screen name="Start">
		<p:output name="APP DEMO" description="demo app" type="text" /> 
		<p:transition name="Start " description="start app" target="Main" /> 
		<p:transition name="Settings" description="modify app settings" 
			target="Settings"/> 
	</p:screen>

	<p:screen name="Main">
		<p:output name="Demo App" description="som text for infos" type="text" /> 
		<p:input name="search something" description="enter a text" /> 
		<p:input name="Check it" description="check Stuff" type="checkbox" /> 
		<p:action function="PeformTask" name="Peform a Task" 
			description="template for a function"/> 
	</p:screen>

	<p:screen name="Settings">
		<p:output name="Settings" description="app settings" type="text" /> 
	</p:screen>
</p:app>

=== elmarkrainz/accapto/Accapto_Generator/new_model.xml
<?xml version="1.0" encoding="UTF-8"?>

<p:app appname="RoutingappAAATE_upd51" package="org.accapto.routingapp"
xmlns:p="org.accapto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.accaptp accapto_model.xsd">
<p:profile>normal</p:profile>


<p:screen name="RoutingTarget">
	<p:output name="Routing Target" description="enter a routing target" type="text" /> 
	<p:input name="search target" description="enter a routing target" /> 
	<p:action function="calculateRoute" name="calculate Route" description="calculate Route" /> 
	<p:transition description="shwo Route overview" name="route Overview" target="RoutingOverview" /> 
</p:screen>

<p:screen name="RoutingOverview">
	<p:output name="Routing Overview" description="Routing Overview" type="text" /> 
	<p:output name="Overview " description="description of the calucaled route" type="text" /> 
	<p:action function="startRouting" name="start routing" description="start Routing" /> 
	<p:transition description="new Route" name="select new routing target" target="RoutingTarget" /> 
</p:screen>

<p:screen name="RoutingDetails">
	<p:output name="Routing Details" description="Routing Details" type="text" /> 
	<p:output name="Direction" description="moving direction" type="text" /> 
	<p:output name="directionsymbol" description="moving direction" type="image" /> 
</p:screen>


<p:screen name="Settings">
	<p:output name="Settings" description="app settings" type="text" /> 
	
</p:screen>


<p:screen name="Start">
	
	<p:output name="ROUTING APP DEMO" description="demo app" type="text" /> 

	<p:transition name="Start " description="select routing target" target="RoutingTarget" /> 
	<p:transition name="Settings" description="modify app settings" target="Settings" /> 
</p:screen>

</p:app>

=== elmarkrainz/accapto/Accapto_Generator/accapto_model_routingapp.xml
<?xml version="1.0" encoding="UTF-8"?>

<p:app appname="WhereAmI-App1" package="org.accepto.app.whereami"
	xmlns:p="org.accapto" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="org.accaptp accapto_model.xsd ">
	<p:profile>no restrictions</p:profile>
	

	<p:screen name="Main">
			<p:output description="zeige meine position" name="Meine Position" type="text" />
			<p:action function="getPostition" name="Position bestimmen" description=""/>
			<p:output name="position" description="" />
			
	</p:screen>
		<p:screen name="Juli">
		<p:output description="" name="Hallo Julian" type="text" />
		<p:input name="Ziel" description="geben Sie das Ziel ein" />
			
	</p:screen>
	
	<p:screen description="" name="Start">
		<p:output description="" name="Start: Wo bin ich" type="text" />
		<p:transition description="open main" name=" zur Main" target="Main" />
		<p:transition description="open main" name=" zu Julian" target="Juli" />
		<p:transition description="open main" name="A11y Settings " target="A12ySettingsActivity" />
	</p:screen>
	
	
	
	
	
	
</p:app>
